// Code generated by protoc-gen-protomcp. DO NOT EDIT.
// source: simple/v1/simple.proto

package v1

import (
	"darvaza.org/core"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// NoImplSimpleMessage provides a no-op implementation of ISimpleMessage.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplSimpleMessage struct{}

// Ensure NoImplSimpleMessage implements ISimpleMessage
var _ ISimpleMessage = (*NoImplSimpleMessage)(nil)

// GetId implements ISimpleMessage.GetId
func (*NoImplSimpleMessage) GetId() string {
	var zero string
	return zero
}

// SetId implements ISimpleMessage.SetId
func (*NoImplSimpleMessage) SetId(v string) error {
	return core.Wrap(core.ErrNotImplemented, "ISimpleMessage.SetId")
}

// GetValue implements ISimpleMessage.GetValue
func (*NoImplSimpleMessage) GetValue() int32 {
	var zero int32
	return zero
}

// SetValue implements ISimpleMessage.SetValue
func (*NoImplSimpleMessage) SetValue(v int32) error {
	return core.Wrap(core.ErrNotImplemented, "ISimpleMessage.SetValue")
}

// ProtoReflect implements ISimpleMessage.ProtoReflect
func (*NoImplSimpleMessage) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements ISimpleMessage.Reset
func (*NoImplSimpleMessage) Reset() {}

// String implements ISimpleMessage.String
func (*NoImplSimpleMessage) String() string {
	return "NoImplSimpleMessage{}"
}
