// Code generated by protoc-gen-protomcp. DO NOT EDIT.
// source: simple/v1/simple.proto

package v1

// ISimpleMessage is the interface for SimpleMessage
// SimpleMessage has no associated service
type ISimpleMessage interface {

	// GetId returns the id field
	GetId() string
	// SetId sets the id field
	SetId(v string) error

	// GetValue returns the value field
	GetValue() int32
	// SetValue sets the value field
	SetValue(v int32) error
}
