// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: simple/v1/simple.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SimpleMessage has no associated service
type SimpleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_simple_v1_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimpleMessage) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_simple_v1_simple_proto protoreflect.FileDescriptor

const file_simple_v1_simple_proto_rawDesc = "" +
	"\n" +
	"\x16simple/v1/simple.proto\x12\tsimple.v1\"5\n" +
	"\rSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05valueB0Z.protomcp.org/protomcp/proto/examples/simple/v1b\x06proto3"

var (
	file_simple_v1_simple_proto_rawDescOnce sync.Once
	file_simple_v1_simple_proto_rawDescData []byte
)

func file_simple_v1_simple_proto_rawDescGZIP() []byte {
	file_simple_v1_simple_proto_rawDescOnce.Do(func() {
		file_simple_v1_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simple_v1_simple_proto_rawDesc), len(file_simple_v1_simple_proto_rawDesc)))
	})
	return file_simple_v1_simple_proto_rawDescData
}

var file_simple_v1_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_simple_v1_simple_proto_goTypes = []any{
	(*SimpleMessage)(nil), // 0: simple.v1.SimpleMessage
}
var file_simple_v1_simple_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simple_v1_simple_proto_init() }
func file_simple_v1_simple_proto_init() {
	if File_simple_v1_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simple_v1_simple_proto_rawDesc), len(file_simple_v1_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simple_v1_simple_proto_goTypes,
		DependencyIndexes: file_simple_v1_simple_proto_depIdxs,
		MessageInfos:      file_simple_v1_simple_proto_msgTypes,
	}.Build()
	File_simple_v1_simple_proto = out.File
	file_simple_v1_simple_proto_goTypes = nil
	file_simple_v1_simple_proto_depIdxs = nil
}
