// Package protomcp provides the core library for ProtoMCP protocol
// implementations, including JSON-RPC 2.0, MCP (Model Context Protocol),
// and REST dispatchers. This package contains the runtime support for
// code generated by protoc-gen-protomcp.
//
// # Protocol Support
//
// The package implements three protocol dispatchers:
//
//   - JSON-RPC 2.0: Built on sourcegraph/jsonrpc2 for reliability
//   - MCP: Anthropic's Model Context Protocol for AI assistant integration
//   - REST: HTTP/REST endpoints using google.api.http annotations
//
// # Core Components
//
//   - Protocol-specific dispatchers that route messages to service implementations
//   - Transport abstractions for HTTP/2 and QUIC
//   - JSON Schema validation for request/response type safety
//   - Middleware support using darvaza.org/x/web
//   - Error handling with protocol-specific mappings
//
// # Integration
//
// This package integrates with:
//
//   - darvaza.org/core for error handling and utilities
//   - darvaza.org/slog for structured logging
//   - encoding/json/v2 for modern JSON handling
//
// Generated code imports this package to access protocol implementations,
// validation utilities, and transport servers.
package protomcp
