// Code generated by protoc-gen-protomcp. DO NOT EDIT.
// source: calculator/v1/calculator.proto

package v1

import (
	"context"

	"darvaza.org/core"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// NoImplAddRequest provides a no-op implementation of IAddRequest.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplAddRequest struct{}

// Ensure NoImplAddRequest implements IAddRequest
var _ IAddRequest = (*NoImplAddRequest)(nil)

// GetA implements IAddRequest.GetA
func (*NoImplAddRequest) GetA() float64 {
	var zero float64
	return zero
}

// SetA implements IAddRequest.SetA
func (*NoImplAddRequest) SetA(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IAddRequest.SetA")
}

// GetB implements IAddRequest.GetB
func (*NoImplAddRequest) GetB() float64 {
	var zero float64
	return zero
}

// SetB implements IAddRequest.SetB
func (*NoImplAddRequest) SetB(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IAddRequest.SetB")
}

// ProtoReflect implements IAddRequest.ProtoReflect
func (*NoImplAddRequest) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IAddRequest.Reset
func (*NoImplAddRequest) Reset() {}

// String implements IAddRequest.String
func (*NoImplAddRequest) String() string {
	return "NoImplAddRequest{}"
}

// NoImplAddResponse provides a no-op implementation of IAddResponse.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplAddResponse struct{}

// Ensure NoImplAddResponse implements IAddResponse
var _ IAddResponse = (*NoImplAddResponse)(nil)

// GetResult implements IAddResponse.GetResult
func (*NoImplAddResponse) GetResult() float64 {
	var zero float64
	return zero
}

// SetResult implements IAddResponse.SetResult
func (*NoImplAddResponse) SetResult(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IAddResponse.SetResult")
}

// ProtoReflect implements IAddResponse.ProtoReflect
func (*NoImplAddResponse) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IAddResponse.Reset
func (*NoImplAddResponse) Reset() {}

// String implements IAddResponse.String
func (*NoImplAddResponse) String() string {
	return "NoImplAddResponse{}"
}

// NoImplMultiplyRequest provides a no-op implementation of IMultiplyRequest.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplMultiplyRequest struct{}

// Ensure NoImplMultiplyRequest implements IMultiplyRequest
var _ IMultiplyRequest = (*NoImplMultiplyRequest)(nil)

// GetA implements IMultiplyRequest.GetA
func (*NoImplMultiplyRequest) GetA() float64 {
	var zero float64
	return zero
}

// SetA implements IMultiplyRequest.SetA
func (*NoImplMultiplyRequest) SetA(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IMultiplyRequest.SetA")
}

// GetB implements IMultiplyRequest.GetB
func (*NoImplMultiplyRequest) GetB() float64 {
	var zero float64
	return zero
}

// SetB implements IMultiplyRequest.SetB
func (*NoImplMultiplyRequest) SetB(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IMultiplyRequest.SetB")
}

// ProtoReflect implements IMultiplyRequest.ProtoReflect
func (*NoImplMultiplyRequest) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IMultiplyRequest.Reset
func (*NoImplMultiplyRequest) Reset() {}

// String implements IMultiplyRequest.String
func (*NoImplMultiplyRequest) String() string {
	return "NoImplMultiplyRequest{}"
}

// NoImplMultiplyResponse provides a no-op implementation of IMultiplyResponse.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplMultiplyResponse struct{}

// Ensure NoImplMultiplyResponse implements IMultiplyResponse
var _ IMultiplyResponse = (*NoImplMultiplyResponse)(nil)

// GetResult implements IMultiplyResponse.GetResult
func (*NoImplMultiplyResponse) GetResult() float64 {
	var zero float64
	return zero
}

// SetResult implements IMultiplyResponse.SetResult
func (*NoImplMultiplyResponse) SetResult(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IMultiplyResponse.SetResult")
}

// ProtoReflect implements IMultiplyResponse.ProtoReflect
func (*NoImplMultiplyResponse) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IMultiplyResponse.Reset
func (*NoImplMultiplyResponse) Reset() {}

// String implements IMultiplyResponse.String
func (*NoImplMultiplyResponse) String() string {
	return "NoImplMultiplyResponse{}"
}

// NoImplDivideRequest provides a no-op implementation of IDivideRequest.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplDivideRequest struct{}

// Ensure NoImplDivideRequest implements IDivideRequest
var _ IDivideRequest = (*NoImplDivideRequest)(nil)

// GetA implements IDivideRequest.GetA
func (*NoImplDivideRequest) GetA() float64 {
	var zero float64
	return zero
}

// SetA implements IDivideRequest.SetA
func (*NoImplDivideRequest) SetA(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IDivideRequest.SetA")
}

// GetB implements IDivideRequest.GetB
func (*NoImplDivideRequest) GetB() float64 {
	var zero float64
	return zero
}

// SetB implements IDivideRequest.SetB
func (*NoImplDivideRequest) SetB(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IDivideRequest.SetB")
}

// ProtoReflect implements IDivideRequest.ProtoReflect
func (*NoImplDivideRequest) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IDivideRequest.Reset
func (*NoImplDivideRequest) Reset() {}

// String implements IDivideRequest.String
func (*NoImplDivideRequest) String() string {
	return "NoImplDivideRequest{}"
}

// NoImplDivideResponse provides a no-op implementation of IDivideResponse.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplDivideResponse struct{}

// Ensure NoImplDivideResponse implements IDivideResponse
var _ IDivideResponse = (*NoImplDivideResponse)(nil)

// GetQuotient implements IDivideResponse.GetQuotient
func (*NoImplDivideResponse) GetQuotient() float64 {
	var zero float64
	return zero
}

// SetQuotient implements IDivideResponse.SetQuotient
func (*NoImplDivideResponse) SetQuotient(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IDivideResponse.SetQuotient")
}

// GetRemainder implements IDivideResponse.GetRemainder
func (*NoImplDivideResponse) GetRemainder() float64 {
	var zero float64
	return zero
}

// SetRemainder implements IDivideResponse.SetRemainder
func (*NoImplDivideResponse) SetRemainder(v float64) error {
	return core.Wrap(core.ErrNotImplemented, "IDivideResponse.SetRemainder")
}

// GetError implements IDivideResponse.GetError
func (*NoImplDivideResponse) GetError() string {
	var zero string
	return zero
}

// SetError implements IDivideResponse.SetError
func (*NoImplDivideResponse) SetError(v string) error {
	return core.Wrap(core.ErrNotImplemented, "IDivideResponse.SetError")
}

// HasError implements IDivideResponse.HasError
func (*NoImplDivideResponse) HasError() bool {
	return false
}

// ClearError implements IDivideResponse.ClearError
func (*NoImplDivideResponse) ClearError() {
	// No-op
}

// ProtoReflect implements IDivideResponse.ProtoReflect
func (*NoImplDivideResponse) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IDivideResponse.Reset
func (*NoImplDivideResponse) Reset() {}

// String implements IDivideResponse.String
func (*NoImplDivideResponse) String() string {
	return "NoImplDivideResponse{}"
}

// NoImplComplexMessage provides a no-op implementation of IComplexMessage.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplComplexMessage struct{}

// Ensure NoImplComplexMessage implements IComplexMessage
var _ IComplexMessage = (*NoImplComplexMessage)(nil)

// GetId implements IComplexMessage.GetId
func (*NoImplComplexMessage) GetId() string {
	var zero string
	return zero
}

// SetId implements IComplexMessage.SetId
func (*NoImplComplexMessage) SetId(v string) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetId")
}

// GetCount implements IComplexMessage.GetCount
func (*NoImplComplexMessage) GetCount() int32 {
	var zero int32
	return zero
}

// SetCount implements IComplexMessage.SetCount
func (*NoImplComplexMessage) SetCount(v int32) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetCount")
}

// GetActive implements IComplexMessage.GetActive
func (*NoImplComplexMessage) GetActive() bool {
	var zero bool
	return zero
}

// SetActive implements IComplexMessage.SetActive
func (*NoImplComplexMessage) SetActive(v bool) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetActive")
}

// GetDescription implements IComplexMessage.GetDescription
func (*NoImplComplexMessage) GetDescription() string {
	var zero string
	return zero
}

// SetDescription implements IComplexMessage.SetDescription
func (*NoImplComplexMessage) SetDescription(v string) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetDescription")
}

// HasDescription implements IComplexMessage.HasDescription
func (*NoImplComplexMessage) HasDescription() bool {
	return false
}

// ClearDescription implements IComplexMessage.ClearDescription
func (*NoImplComplexMessage) ClearDescription() {
	// No-op
}

// GetTags implements IComplexMessage.GetTags
func (*NoImplComplexMessage) GetTags() []string {
	var zero []string
	return zero
}

// SetTags implements IComplexMessage.SetTags
func (*NoImplComplexMessage) SetTags(v []string) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetTags")
}

// GetMetadata implements IComplexMessage.GetMetadata
func (*NoImplComplexMessage) GetMetadata() map[string]string {
	return nil
}

// SetMetadata implements IComplexMessage.SetMetadata
func (*NoImplComplexMessage) SetMetadata(v map[string]string) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetMetadata")
}

// GetUser implements IComplexMessage.GetUser
func (*NoImplComplexMessage) GetUser() IUserInfo {
	return nil
}

// SetUser implements IComplexMessage.SetUser
func (*NoImplComplexMessage) SetUser(v IUserInfo) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetUser")
}

// GetStatus implements IComplexMessage.GetStatus
func (*NoImplComplexMessage) GetStatus() Status {
	var zero Status
	return zero
}

// SetStatus implements IComplexMessage.SetStatus
func (*NoImplComplexMessage) SetStatus(v Status) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetStatus")
}

// GetIdentifier implements IComplexMessage.GetIdentifier
func (*NoImplComplexMessage) GetIdentifier() isComplexMessage_Identifier {
	return nil
}

// SetEmail implements IComplexMessage.SetEmail
func (*NoImplComplexMessage) SetEmail(v string) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetEmail")
}

// SetUsername implements IComplexMessage.SetUsername
func (*NoImplComplexMessage) SetUsername(v string) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetUsername")
}

// SetUserId implements IComplexMessage.SetUserId
func (*NoImplComplexMessage) SetUserId(v int64) error {
	return core.Wrap(core.ErrNotImplemented, "IComplexMessage.SetUserId")
}

// ProtoReflect implements IComplexMessage.ProtoReflect
func (*NoImplComplexMessage) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IComplexMessage.Reset
func (*NoImplComplexMessage) Reset() {}

// String implements IComplexMessage.String
func (*NoImplComplexMessage) String() string {
	return "NoImplComplexMessage{}"
}

// NoImplUserInfo provides a no-op implementation of IUserInfo.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplUserInfo struct{}

// Ensure NoImplUserInfo implements IUserInfo
var _ IUserInfo = (*NoImplUserInfo)(nil)

// GetName implements IUserInfo.GetName
func (*NoImplUserInfo) GetName() string {
	var zero string
	return zero
}

// SetName implements IUserInfo.SetName
func (*NoImplUserInfo) SetName(v string) error {
	return core.Wrap(core.ErrNotImplemented, "IUserInfo.SetName")
}

// GetAge implements IUserInfo.GetAge
func (*NoImplUserInfo) GetAge() int32 {
	var zero int32
	return zero
}

// SetAge implements IUserInfo.SetAge
func (*NoImplUserInfo) SetAge(v int32) error {
	return core.Wrap(core.ErrNotImplemented, "IUserInfo.SetAge")
}

// ProtoReflect implements IUserInfo.ProtoReflect
func (*NoImplUserInfo) ProtoReflect() protoreflect.Message {
	return nil
}

// Reset implements IUserInfo.Reset
func (*NoImplUserInfo) Reset() {}

// String implements IUserInfo.String
func (*NoImplUserInfo) String() string {
	return "NoImplUserInfo{}"
}

// NoImplCalculatorService provides a no-op implementation of ICalculatorService.
// Embed this struct in your implementation to forward unimplemented methods.
type NoImplCalculatorService struct{}

// Ensure NoImplCalculatorService implements ICalculatorService
var _ ICalculatorService = (*NoImplCalculatorService)(nil)

// Add implements ICalculatorService.Add
func (*NoImplCalculatorService) Add(ctx context.Context, req IAddRequest) (IAddResponse, error) {
	return nil, core.Wrap(core.ErrNotImplemented, "ICalculatorService.Add")
}

// Multiply implements ICalculatorService.Multiply
func (*NoImplCalculatorService) Multiply(ctx context.Context, req IMultiplyRequest) (IMultiplyResponse, error) {
	return nil, core.Wrap(core.ErrNotImplemented, "ICalculatorService.Multiply")
}

// Divide implements ICalculatorService.Divide
func (*NoImplCalculatorService) Divide(ctx context.Context, req IDivideRequest) (IDivideResponse, error) {
	return nil, core.Wrap(core.ErrNotImplemented, "ICalculatorService.Divide")
}
