// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: calculator/v1/calculator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum type
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
	Status_STATUS_SUSPENDED   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_SUSPENDED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
		"STATUS_SUSPENDED":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_calculator_v1_calculator_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_calculator_v1_calculator_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

// AddRequest is the request message for Add method
type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

// AddResponse is the response message for Add method
type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// MultiplyRequest is the request message for Multiply method
type MultiplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiplyRequest) Reset() {
	*x = MultiplyRequest{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyRequest) ProtoMessage() {}

func (x *MultiplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplyRequest.ProtoReflect.Descriptor instead.
func (*MultiplyRequest) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *MultiplyRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *MultiplyRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

// MultiplyResponse is the response message for Multiply method
type MultiplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiplyResponse) Reset() {
	*x = MultiplyResponse{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyResponse) ProtoMessage() {}

func (x *MultiplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplyResponse.ProtoReflect.Descriptor instead.
func (*MultiplyResponse) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *MultiplyResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// DivideRequest is the request message for Divide method
type DivideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivideRequest) Reset() {
	*x = DivideRequest{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivideRequest) ProtoMessage() {}

func (x *DivideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivideRequest.ProtoReflect.Descriptor instead.
func (*DivideRequest) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *DivideRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *DivideRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

// DivideResponse is the response message for Divide method
type DivideResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Quotient  float64                `protobuf:"fixed64,1,opt,name=quotient,proto3" json:"quotient,omitempty"`
	Remainder float64                `protobuf:"fixed64,2,opt,name=remainder,proto3" json:"remainder,omitempty"`
	// Error message if division by zero
	Error         *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivideResponse) Reset() {
	*x = DivideResponse{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivideResponse) ProtoMessage() {}

func (x *DivideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivideResponse.ProtoReflect.Descriptor instead.
func (*DivideResponse) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{5}
}

func (x *DivideResponse) GetQuotient() float64 {
	if x != nil {
		return x.Quotient
	}
	return 0
}

func (x *DivideResponse) GetRemainder() float64 {
	if x != nil {
		return x.Remainder
	}
	return 0
}

func (x *DivideResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Complex example with various field types
type ComplexMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scalar types
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	// Optional field
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Repeated field
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Map field
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Nested message
	User *UserInfo `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	// Oneof field
	//
	// Types that are valid to be assigned to Identifier:
	//
	//	*ComplexMessage_Email
	//	*ComplexMessage_Username
	//	*ComplexMessage_UserId
	Identifier isComplexMessage_Identifier `protobuf_oneof:"identifier"`
	// Enum field
	Status        Status `protobuf:"varint,11,opt,name=status,proto3,enum=calculator.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexMessage) Reset() {
	*x = ComplexMessage{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexMessage) ProtoMessage() {}

func (x *ComplexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexMessage.ProtoReflect.Descriptor instead.
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{6}
}

func (x *ComplexMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComplexMessage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ComplexMessage) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ComplexMessage) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ComplexMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ComplexMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ComplexMessage) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ComplexMessage) GetIdentifier() isComplexMessage_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ComplexMessage) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*ComplexMessage_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *ComplexMessage) GetUsername() string {
	if x != nil {
		if x, ok := x.Identifier.(*ComplexMessage_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *ComplexMessage) GetUserId() int64 {
	if x != nil {
		if x, ok := x.Identifier.(*ComplexMessage_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *ComplexMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type isComplexMessage_Identifier interface {
	isComplexMessage_Identifier()
}

type ComplexMessage_Email struct {
	Email string `protobuf:"bytes,8,opt,name=email,proto3,oneof"`
}

type ComplexMessage_Username struct {
	Username string `protobuf:"bytes,9,opt,name=username,proto3,oneof"`
}

type ComplexMessage_UserId struct {
	UserId int64 `protobuf:"varint,10,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*ComplexMessage_Email) isComplexMessage_Identifier() {}

func (*ComplexMessage_Username) isComplexMessage_Identifier() {}

func (*ComplexMessage_UserId) isComplexMessage_Identifier() {}

// Nested message type
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_calculator_v1_calculator_proto protoreflect.FileDescriptor

const file_calculator_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1ecalculator/v1/calculator.proto\x12\rcalculator.v1\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\"%\n" +
	"\vAddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"-\n" +
	"\x0fMultiplyRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\"*\n" +
	"\x10MultiplyResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"+\n" +
	"\rDivideRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\"o\n" +
	"\x0eDivideResponse\x12\x1a\n" +
	"\bquotient\x18\x01 \x01(\x01R\bquotient\x12\x1c\n" +
	"\tremainder\x18\x02 \x01(\x01R\tremainder\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xda\x03\n" +
	"\x0eComplexMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.calculator.v1.ComplexMessage.MetadataEntryR\bmetadata\x12+\n" +
	"\x04user\x18\a \x01(\v2\x17.calculator.v1.UserInfoR\x04user\x12\x16\n" +
	"\x05email\x18\b \x01(\tH\x00R\x05email\x12\x1c\n" +
	"\busername\x18\t \x01(\tH\x00R\busername\x12\x19\n" +
	"\auser_id\x18\n" +
	" \x01(\x03H\x00R\x06userId\x12-\n" +
	"\x06status\x18\v \x01(\x0e2\x15.calculator.v1.StatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"identifierB\x0e\n" +
	"\f_description\"0\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age*^\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x032\xe5\x01\n" +
	"\x11CalculatorService\x12<\n" +
	"\x03Add\x12\x19.calculator.v1.AddRequest\x1a\x1a.calculator.v1.AddResponse\x12K\n" +
	"\bMultiply\x12\x1e.calculator.v1.MultiplyRequest\x1a\x1f.calculator.v1.MultiplyResponse\x12E\n" +
	"\x06Divide\x12\x1c.calculator.v1.DivideRequest\x1a\x1d.calculator.v1.DivideResponseB4Z2protomcp.org/protomcp/proto/examples/calculator/v1b\x06proto3"

var (
	file_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_calculator_v1_calculator_proto_rawDescData []byte
)

func file_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)))
	})
	return file_calculator_v1_calculator_proto_rawDescData
}

var file_calculator_v1_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_calculator_v1_calculator_proto_goTypes = []any{
	(Status)(0),              // 0: calculator.v1.Status
	(*AddRequest)(nil),       // 1: calculator.v1.AddRequest
	(*AddResponse)(nil),      // 2: calculator.v1.AddResponse
	(*MultiplyRequest)(nil),  // 3: calculator.v1.MultiplyRequest
	(*MultiplyResponse)(nil), // 4: calculator.v1.MultiplyResponse
	(*DivideRequest)(nil),    // 5: calculator.v1.DivideRequest
	(*DivideResponse)(nil),   // 6: calculator.v1.DivideResponse
	(*ComplexMessage)(nil),   // 7: calculator.v1.ComplexMessage
	(*UserInfo)(nil),         // 8: calculator.v1.UserInfo
	nil,                      // 9: calculator.v1.ComplexMessage.MetadataEntry
}
var file_calculator_v1_calculator_proto_depIdxs = []int32{
	9, // 0: calculator.v1.ComplexMessage.metadata:type_name -> calculator.v1.ComplexMessage.MetadataEntry
	8, // 1: calculator.v1.ComplexMessage.user:type_name -> calculator.v1.UserInfo
	0, // 2: calculator.v1.ComplexMessage.status:type_name -> calculator.v1.Status
	1, // 3: calculator.v1.CalculatorService.Add:input_type -> calculator.v1.AddRequest
	3, // 4: calculator.v1.CalculatorService.Multiply:input_type -> calculator.v1.MultiplyRequest
	5, // 5: calculator.v1.CalculatorService.Divide:input_type -> calculator.v1.DivideRequest
	2, // 6: calculator.v1.CalculatorService.Add:output_type -> calculator.v1.AddResponse
	4, // 7: calculator.v1.CalculatorService.Multiply:output_type -> calculator.v1.MultiplyResponse
	6, // 8: calculator.v1.CalculatorService.Divide:output_type -> calculator.v1.DivideResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_calculator_v1_calculator_proto_init() }
func file_calculator_v1_calculator_proto_init() {
	if File_calculator_v1_calculator_proto != nil {
		return
	}
	file_calculator_v1_calculator_proto_msgTypes[5].OneofWrappers = []any{}
	file_calculator_v1_calculator_proto_msgTypes[6].OneofWrappers = []any{
		(*ComplexMessage_Email)(nil),
		(*ComplexMessage_Username)(nil),
		(*ComplexMessage_UserId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_v1_calculator_proto_depIdxs,
		EnumInfos:         file_calculator_v1_calculator_proto_enumTypes,
		MessageInfos:      file_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_calculator_v1_calculator_proto = out.File
	file_calculator_v1_calculator_proto_goTypes = nil
	file_calculator_v1_calculator_proto_depIdxs = nil
}
